// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizjfe_QlSzz55SwaiQz0sOYVUoSf_GzY',
    appId: '1:942144436665:web:your_web_app_id',
    messagingSenderId: '942144436665',
    projectId: 'parole-du-mome',
    authDomain: 'parole-du-mome.firebaseapp.com',
    storageBucket: 'parole-du-mome.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAizjfe_QlSzz55SwaiQz0sOYVUoSf_GzY',
    appId: '1:942144436665:android:077432ba881f8babc21e68',
    messagingSenderId: '942144436665',
    projectId: 'parole-du-mome',
    storageBucket: 'parole-du-mome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAizjfe_QlSzz55SwaiQz0sOYVUoSf_GzY',
    appId: '1:942144436665:ios:your_ios_app_id',
    messagingSenderId: '942144436665',
    projectId: 'parole-du-mome',
    storageBucket: 'parole-du-mome.firebasestorage.app',
    iosBundleId: 'com.example.paroleDuMoment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAizjfe_QlSzz55SwaiQz0sOYVUoSf_GzY',
    appId: '1:942144436665:ios:your_macos_app_id',
    messagingSenderId: '942144436665',
    projectId: 'parole-du-mome',
    storageBucket: 'parole-du-mome.firebasestorage.app',
    iosBundleId: 'com.example.paroleDuMoment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizjfe_QlSzz55SwaiQz0sOYVUoSf_GzY',
    appId: '1:942144436665:web:your_windows_app_id',
    messagingSenderId: '942144436665',
    projectId: 'parole-du-mome',
    authDomain: 'parole-du-mome.firebaseapp.com',
    storageBucket: 'parole-du-mome.firebasestorage.app',
  );
}
